version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: hexagon-redis
    ports:
      - '6379:6379'
  postgres:
    image: postgres:latest
    container_name: hexagon-postgres
    restart: always
    env_file:
      - ./docker/.env
    ports:
      - '5432:5432'
